version: '3.1'

services:
  web:
    build: .
    container_name: php_web
    restart: always
    ports:
      - "8000:80"
    volumes:
      - /home/nasri/www/security:/var/www/html
    networks:
      - app-network
  web2:
    build: .
    container_name: php_web_2
    restart: always
    ports:
      - "8100:80"
    volumes:
      - /home/nasri/www/attacker-code:/var/www/html
    networks:
      - app-network
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: security_lab_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
